/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.ImageIcon;
import Classes.Prices;
import Conecction.Conecction;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Classes.Tour;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aleja
 */
public class Admin extends javax.swing.JFrame {
     private Conecction conn;
     ArrayList<Tour> tourAr = new ArrayList<Tour>();
     JTable tabla;
     ResultSet rs,rs2;

    /**
     * Creates new form book_cliente
     */
    public Admin() {
        initComponents();
        this.conn = new Conecction();
        this.mod_tour.setVisible(false);
        this.admin_ven.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        ModificarTour = new javax.swing.JButton();
        AdminVendedores = new javax.swing.JButton();
        MostrarTours = new javax.swing.JButton();
        admin_ven = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLogIn = new javax.swing.JTable();
        mod_tour = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tourName1 = new javax.swing.JLabel();
        Price1_MX1 = new javax.swing.JTextField();
        Price1_MX2 = new javax.swing.JTextField();
        Price1_MX3 = new javax.swing.JTextField();
        Price1_US1 = new javax.swing.JTextField();
        Price1_US2 = new javax.swing.JTextField();
        Price1_US3 = new javax.swing.JTextField();
        Cap1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tourName2 = new javax.swing.JLabel();
        Price2_MX1 = new javax.swing.JTextField();
        Price2_MX2 = new javax.swing.JTextField();
        Price2_MX3 = new javax.swing.JTextField();
        Price2_US1 = new javax.swing.JTextField();
        Price2_US2 = new javax.swing.JTextField();
        Price2_US3 = new javax.swing.JTextField();
        Cap2 = new javax.swing.JTextField();
        Price3_MX2 = new javax.swing.JTextField();
        tourName3 = new javax.swing.JLabel();
        Price3_MX1 = new javax.swing.JTextField();
        Price3_US3 = new javax.swing.JTextField();
        Cap3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Price3_MX3 = new javax.swing.JTextField();
        Price3_US2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Price3_US1 = new javax.swing.JTextField();
        UpdateTour1 = new javax.swing.JButton();
        UpdateTour2 = new javax.swing.JButton();
        UpdateTour3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Hora1_1 = new javax.swing.JTextField();
        Hora1_2 = new javax.swing.JTextField();
        Hora1_3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Hora2_1 = new javax.swing.JTextField();
        Hora2_2 = new javax.swing.JTextField();
        Hora2_3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Hora3_1 = new javax.swing.JTextField();
        Hora3_2 = new javax.swing.JTextField();
        Hora3_3 = new javax.swing.JTextField();
        inc_tours = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tour_table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_panel.setBackground(new java.awt.Color(255, 255, 255));

        ModificarTour.setText("Modificar tour");
        ModificarTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTourActionPerformed(evt);
            }
        });

        AdminVendedores.setText("Administrar vendedores");
        AdminVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminVendedoresActionPerformed(evt);
            }
        });

        MostrarTours.setText("Mostrar Tours");
        MostrarTours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarToursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(MostrarTours, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addComponent(AdminVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, main_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModificarTour, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(504, 504, 504))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(MostrarTours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addComponent(ModificarTour, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        getContentPane().add(main_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -25, 1300, 670));

        admin_ven.setBackground(new java.awt.Color(255, 255, 255));

        tablaLogIn.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tablaLogIn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User#", "UserID", "Password", "Level"
            }
        ));
        tablaLogIn.setEnabled(false);
        jScrollPane1.setViewportView(tablaLogIn);

        javax.swing.GroupLayout admin_venLayout = new javax.swing.GroupLayout(admin_ven);
        admin_ven.setLayout(admin_venLayout);
        admin_venLayout.setHorizontalGroup(
            admin_venLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_venLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(556, Short.MAX_VALUE))
        );
        admin_venLayout.setVerticalGroup(
            admin_venLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_venLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );

        getContentPane().add(admin_ven, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -25, 1300, 670));

        mod_tour.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRECIOS");

        jLabel5.setText("CAPACIDAD");

        tourName1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tourName1.setText("TOURNAME");

        Price1_MX2.setText(" ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("PRECIOS");

        jLabel8.setText("CAPACIDAD");

        tourName2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tourName2.setText("TOURNAME");

        tourName3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tourName3.setText("TOURNAME");

        jLabel11.setText("CAPACIDAD");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PRECIOS");

        UpdateTour1.setText("UPDATE");
        UpdateTour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTour1ActionPerformed(evt);
            }
        });

        UpdateTour2.setText("UPDATE");
        UpdateTour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTour2ActionPerformed(evt);
            }
        });

        UpdateTour3.setText("UPDATE");
        UpdateTour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTour3ActionPerformed(evt);
            }
        });

        jButton1.setText("X");
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("HORARIOS");

        Hora1_2.setText(" ");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("HORARIOS");

        Hora2_2.setText(" ");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HORARIOS");

        Hora3_2.setText(" ");

        javax.swing.GroupLayout mod_tourLayout = new javax.swing.GroupLayout(mod_tour);
        mod_tour.setLayout(mod_tourLayout);
        mod_tourLayout.setHorizontalGroup(
            mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(mod_tourLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Price1_US1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price1_US2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Price1_US3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UpdateTour1)
                            .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mod_tourLayout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel5))
                                .addGroup(mod_tourLayout.createSequentialGroup()
                                    .addComponent(Price1_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(30, 30, 30)
                                    .addComponent(Cap1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Price1_MX2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price1_MX3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(tourName1)))
                .addGap(60, 60, 60)
                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                                .addComponent(Price2_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(Cap2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateTour2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Price2_MX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price2_MX3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price2_US1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price2_US2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price2_US3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tourName2)))
                .addGap(53, 53, 53)
                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                                .addComponent(Price3_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(Cap3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UpdateTour3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Price3_MX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price3_MX3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price3_US1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price3_US2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Price3_US3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hora3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tourName3)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        mod_tourLayout.setVerticalGroup(
            mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(UpdateTour3))
                    .addGroup(mod_tourLayout.createSequentialGroup()
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mod_tourLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(59, 59, 59))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mod_tourLayout.createSequentialGroup()
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tourName1)
                                    .addComponent(tourName3))
                                .addGap(18, 18, 18)))
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mod_tourLayout.createSequentialGroup()
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mod_tourLayout.createSequentialGroup()
                                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Price1_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cap1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addComponent(Price1_MX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price1_MX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price1_US1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price1_US2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price1_US3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mod_tourLayout.createSequentialGroup()
                                        .addComponent(Hora1_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Hora1_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Hora1_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                                .addComponent(UpdateTour1))
                            .addGroup(mod_tourLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mod_tourLayout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(Hora3_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Hora3_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Hora3_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(mod_tourLayout.createSequentialGroup()
                                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9)
                                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Price3_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cap3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Price3_MX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price3_MX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price3_US1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price3_US2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(Price3_US3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mod_tourLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mod_tourLayout.createSequentialGroup()
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(mod_tourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Price2_MX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cap2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Price2_MX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Price2_MX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Price2_US1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Price2_US2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Price2_US3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(mod_tourLayout.createSequentialGroup()
                                .addComponent(tourName2)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(Hora2_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Hora2_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Hora2_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdateTour2)))))
                .addGap(92, 92, 92))
        );

        getContentPane().add(mod_tour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 650));

        inc_tours.setBackground(new java.awt.Color(255, 255, 255));

        tour_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tour_table);

        javax.swing.GroupLayout inc_toursLayout = new javax.swing.GroupLayout(inc_tours);
        inc_tours.setLayout(inc_toursLayout);
        inc_toursLayout.setHorizontalGroup(
            inc_toursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inc_toursLayout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        inc_toursLayout.setVerticalGroup(
            inc_toursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inc_toursLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );

        getContentPane().add(inc_tours, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -25, 1300, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTourActionPerformed
        // TODO add your handling code here:
        tourAr=this.conn.getTours();
        //Abre ventana de cambios en tours
        this.mod_tour.setVisible(true);
        this.main_panel.setVisible(false);
        //TOUR1
        this.Price1_MX1.setText(Float.toString(tourAr.get(0).precioAdultoMX));
        this.Price1_MX2.setText(Float.toString(tourAr.get(0).precioNinoMX));
        this.Price1_MX3.setText(Float.toString(tourAr.get(0).precioInfanteMX));
        this.Price1_US1.setText(Float.toString(tourAr.get(0).precioAdultoUS));
        this.Price1_US2.setText(Float.toString(tourAr.get(0).precioNinoUS));
        this.Price1_US3.setText(Float.toString(tourAr.get(0).precioInfanteUS));
        this.Cap1.setText(String.valueOf(tourAr.get(0).capacidad));
        this.tourName1.setText(tourAr.get(0).nombre);
        this.Hora1_1.setText(tourAr.get(0).hora1);
        this.Hora1_2.setText(tourAr.get(0).hora2);
        this.Hora1_3.setText(tourAr.get(0).hora3);
        //TOUR2
        this.Price2_MX1.setText(Float.toString(tourAr.get(1).precioAdultoMX));
        this.Price2_MX2.setText(Float.toString(tourAr.get(1).precioNinoMX));
        this.Price2_MX3.setText(Float.toString(tourAr.get(1).precioInfanteMX));
        this.Price2_US1.setText(Float.toString(tourAr.get(1).precioAdultoUS));
        this.Price2_US2.setText(Float.toString(tourAr.get(1).precioNinoUS));
        this.Price2_US3.setText(Float.toString(tourAr.get(1).precioInfanteUS));
        this.Cap2.setText(String.valueOf(tourAr.get(1).capacidad));
        this.tourName2.setText(tourAr.get(1).nombre);
         this.Hora2_1.setText(tourAr.get(1).hora1);
        this.Hora2_2.setText(tourAr.get(1).hora2);
        this.Hora2_3.setText(tourAr.get(1).hora3);
        //TOUR3
        this.Price3_MX1.setText(Float.toString(tourAr.get(2).precioAdultoMX));
        this.Price3_MX2.setText(Float.toString(tourAr.get(2).precioNinoMX));
        this.Price3_MX3.setText(Float.toString(tourAr.get(2).precioInfanteMX));
        this.Price3_US1.setText(Float.toString(tourAr.get(2).precioAdultoUS));
        this.Price3_US2.setText(Float.toString(tourAr.get(2).precioNinoUS));
        this.Price3_US3.setText(Float.toString(tourAr.get(2).precioInfanteUS));
        this.Cap3.setText(String.valueOf(tourAr.get(2).capacidad));
        this.tourName3.setText(tourAr.get(2).nombre);
         this.Hora3_1.setText(tourAr.get(2).hora1);
        this.Hora3_2.setText(tourAr.get(2).hora2);
        this.Hora3_3.setText(tourAr.get(2).hora3);
    }//GEN-LAST:event_ModificarTourActionPerformed

    private void UpdateTour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTour1ActionPerformed
        // TODO add your handling code here:
        this.conn.updateTour(Float.parseFloat(Price1_MX1.getText()), Float.parseFloat(Price1_MX2.getText()),Float.parseFloat( Price1_MX3.getText()),Float.parseFloat( Price1_US1.getText()),Float.parseFloat( Price1_US2.getText()),Float.parseFloat( Price1_US3.getText()), Integer.parseInt(Cap1.getText()),Hora1_1.getText(),Hora1_2.getText(),Hora1_3.getText(), 1);
    }//GEN-LAST:event_UpdateTour1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.mod_tour.setVisible(false);
        this.main_panel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UpdateTour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTour2ActionPerformed
        // TODO add your handling code here:
        this.conn.updateTour(Float.parseFloat(Price2_MX1.getText()), Float.parseFloat(Price2_MX2.getText()),Float.parseFloat( Price2_MX3.getText()),Float.parseFloat( Price2_US1.getText()),Float.parseFloat( Price2_US2.getText()),Float.parseFloat( Price2_US3.getText()), Integer.parseInt(Cap2.getText()),Hora2_1.getText(),Hora2_2.getText(),Hora2_3.getText(), 2);
    }//GEN-LAST:event_UpdateTour2ActionPerformed

    private void UpdateTour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTour3ActionPerformed
        // TODO add your handling code here:
        this.conn.updateTour(Float.parseFloat(Price3_MX1.getText()), Float.parseFloat(Price3_MX2.getText()),Float.parseFloat( Price3_MX3.getText()),Float.parseFloat( Price3_US1.getText()),Float.parseFloat( Price3_US2.getText()),Float.parseFloat( Price3_US3.getText()), Integer.parseInt(Cap3.getText()),Hora3_1.getText(),Hora3_2.getText(),Hora3_3.getText(), 3);
    }//GEN-LAST:event_UpdateTour3ActionPerformed

    private void AdminVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminVendedoresActionPerformed
        // TODO add your handling code here:
        this.admin_ven.setVisible(true);
        this.main_panel.setVisible(false);
        //SE LLENA LA TABLA DE LOGIN
        DefaultTableModel dfm= new DefaultTableModel();
        tabla = this.tablaLogIn;
        tabla.setModel(dfm);
        dfm.setColumnIdentifiers(new Object[]{"User#","UserName","Password","AccesLevel"});
        rs = this.conn.logInUsers();
        String nivel="";
        try { 
            while (rs.next()){
                if(rs.getBoolean("nivel")){
                    nivel="Administrador";
                }
                else{
                    nivel="Vendedor";
                }
                dfm.addRow(new Object[]{rs.getInt("idLogIn"),rs.getString("user"),rs.getString("password"),nivel});
            }
        }catch(Exception e){
            
        }        
    }//GEN-LAST:event_AdminVendedoresActionPerformed

    private void MostrarToursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarToursActionPerformed

        this.inc_tours.setVisible(true);
        this.main_panel.setVisible(false);
        //SE LLENA LA TABLA DE TOURS
        DefaultTableModel dfm2= new DefaultTableModel();
        tabla = this.tour_table;
        tabla.setModel(dfm2);
        dfm2.setColumnIdentifiers(new Object[]{"Tour","Fecha","Horario","Asistentes"});
        rs2 = this.conn.incTours();
        String hora;
        try { 
            while (rs2.next()){
                hora = conn.gethour(rs2.getInt("horario"),rs2.getInt("idtour"));
                dfm2.addRow(new Object[]{rs2.getString("nombre"),rs2.getDate("fecha"),hora,rs2.getInt("turistas")});
            }
        }catch(Exception e){
            
        }  
    }//GEN-LAST:event_MostrarToursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminVendedores;
    private javax.swing.JTextField Cap1;
    private javax.swing.JTextField Cap2;
    private javax.swing.JTextField Cap3;
    private javax.swing.JTextField Hora1_1;
    private javax.swing.JTextField Hora1_2;
    private javax.swing.JTextField Hora1_3;
    private javax.swing.JTextField Hora2_1;
    private javax.swing.JTextField Hora2_2;
    private javax.swing.JTextField Hora2_3;
    private javax.swing.JTextField Hora3_1;
    private javax.swing.JTextField Hora3_2;
    private javax.swing.JTextField Hora3_3;
    private javax.swing.JButton ModificarTour;
    private javax.swing.JButton MostrarTours;
    private javax.swing.JTextField Price1_MX1;
    private javax.swing.JTextField Price1_MX2;
    private javax.swing.JTextField Price1_MX3;
    private javax.swing.JTextField Price1_US1;
    private javax.swing.JTextField Price1_US2;
    private javax.swing.JTextField Price1_US3;
    private javax.swing.JTextField Price2_MX1;
    private javax.swing.JTextField Price2_MX2;
    private javax.swing.JTextField Price2_MX3;
    private javax.swing.JTextField Price2_US1;
    private javax.swing.JTextField Price2_US2;
    private javax.swing.JTextField Price2_US3;
    private javax.swing.JTextField Price3_MX1;
    private javax.swing.JTextField Price3_MX2;
    private javax.swing.JTextField Price3_MX3;
    private javax.swing.JTextField Price3_US1;
    private javax.swing.JTextField Price3_US2;
    private javax.swing.JTextField Price3_US3;
    private javax.swing.JButton UpdateTour1;
    private javax.swing.JButton UpdateTour2;
    private javax.swing.JButton UpdateTour3;
    private javax.swing.JPanel admin_ven;
    private javax.swing.JPanel inc_tours;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel mod_tour;
    private javax.swing.JTable tablaLogIn;
    private javax.swing.JLabel tourName1;
    private javax.swing.JLabel tourName2;
    private javax.swing.JLabel tourName3;
    private javax.swing.JTable tour_table;
    // End of variables declaration//GEN-END:variables
}
