/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.ImageIcon;

/**
 *
 * @author aleja
 */
public class Cancelaciones extends javax.swing.JFrame {

    /**
     * Creates new form Cancelaciones
     */
    public Cancelaciones() {
        initComponents();  
        input_nombre.setOpaque(false);
        input_apellido.setOpaque(false); 
        input_email.setOpaque(false); 
        input_cel.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_cancelaciones = new javax.swing.JPanel();
        NoCuenta = new javax.swing.JPanel();
        title_cancelacionNo = new javax.swing.JLabel();
        cancelacion_name = new javax.swing.JLabel();
        input_nombre = new javax.swing.JTextField();
        input_apellido = new javax.swing.JTextField();
        cancelacion_apellido = new javax.swing.JLabel();
        separador_apellido = new javax.swing.JSeparator();
        input_email = new javax.swing.JTextField();
        cancelacion_email = new javax.swing.JLabel();
        separador_email = new javax.swing.JSeparator();
        cancelacion_cel = new javax.swing.JLabel();
        input_cel = new javax.swing.JTextField();
        separador_cel = new javax.swing.JSeparator();
        btn_buscar_noOrden = new javax.swing.JButton();
        separador_nombre2 = new javax.swing.JSeparator();
        NoOrden = new javax.swing.JPanel();
        cancelacion_noOrden = new javax.swing.JLabel();
        title_numero = new javax.swing.JLabel();
        input_numero = new javax.swing.JTextField();
        separador_numero = new javax.swing.JSeparator();
        btn_buscar_noOrden1 = new javax.swing.JButton();
        Resumen = new javax.swing.JPanel();
        title_cancelacionNo2 = new javax.swing.JLabel();
        title_cancelacion_nombre = new javax.swing.JLabel();
        title_cancelacionNo4 = new javax.swing.JLabel();
        title_cancelacion_noOrdern = new javax.swing.JLabel();
        title_cancelacion_correo = new javax.swing.JLabel();
        title_cancelacion_telefono = new javax.swing.JLabel();
        separador_nombre1 = new javax.swing.JSeparator();
        title_cancelacion_tour = new javax.swing.JLabel();
        tour_cancelacion_nameTour = new javax.swing.JLabel();
        title_cancelacion_date = new javax.swing.JLabel();
        tour_cancelacion_date = new javax.swing.JLabel();
        title_cancelacion_adult = new javax.swing.JLabel();
        tour_cancelacion_adult = new javax.swing.JLabel();
        title_cancelacion_child = new javax.swing.JLabel();
        tour_cancelacion_child = new javax.swing.JLabel();
        title_cancelacion_time = new javax.swing.JLabel();
        title_cancelacion_hora = new javax.swing.JLabel();
        separador_nombre3 = new javax.swing.JSeparator();
        totalPrice = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        moneda = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_cancelaciones.setBackground(new java.awt.Color(255, 255, 255));
        panel_cancelaciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NoCuenta.setBackground(new java.awt.Color(241, 242, 242));
        NoCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_cancelacionNo.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_cancelacionNo.setForeground(new java.awt.Color(0, 123, 164));
        title_cancelacionNo.setText("No cuenta con numero de orden");
        NoCuenta.add(title_cancelacionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        cancelacion_name.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cancelacion_name.setForeground(new java.awt.Color(153, 153, 153));
        cancelacion_name.setText("Nombre:");
        NoCuenta.add(cancelacion_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 80, -1));

        input_nombre.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_nombre.setForeground(new java.awt.Color(153, 153, 153));
        input_nombre.setBorder(null);
        input_nombre.setOpaque(false);
        input_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombreActionPerformed(evt);
            }
        });
        NoCuenta.add(input_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 430, 30));

        input_apellido.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_apellido.setForeground(new java.awt.Color(153, 153, 153));
        input_apellido.setBorder(null);
        input_apellido.setOpaque(false);
        input_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_apellidoActionPerformed(evt);
            }
        });
        NoCuenta.add(input_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 430, 30));

        cancelacion_apellido.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cancelacion_apellido.setForeground(new java.awt.Color(153, 153, 153));
        cancelacion_apellido.setText("Apellido:");
        NoCuenta.add(cancelacion_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 80, -1));
        NoCuenta.add(separador_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 510, 10));

        input_email.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_email.setForeground(new java.awt.Color(153, 153, 153));
        input_email.setBorder(null);
        input_email.setOpaque(false);
        input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_emailActionPerformed(evt);
            }
        });
        NoCuenta.add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 430, 30));

        cancelacion_email.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cancelacion_email.setForeground(new java.awt.Color(153, 153, 153));
        cancelacion_email.setText("Email:");
        NoCuenta.add(cancelacion_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 80, -1));
        NoCuenta.add(separador_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 510, 10));

        cancelacion_cel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        cancelacion_cel.setForeground(new java.awt.Color(153, 153, 153));
        cancelacion_cel.setText("Number:");
        NoCuenta.add(cancelacion_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 80, -1));

        input_cel.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_cel.setForeground(new java.awt.Color(153, 153, 153));
        input_cel.setBorder(null);
        input_cel.setOpaque(false);
        input_cel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_celActionPerformed(evt);
            }
        });
        NoCuenta.add(input_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 430, 30));
        NoCuenta.add(separador_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 510, 10));

        btn_buscar_noOrden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Buscar_Static_10.png"))); // NOI18N
        btn_buscar_noOrden.setBorder(null);
        btn_buscar_noOrden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscar_noOrdenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscar_noOrdenMouseExited(evt);
            }
        });
        btn_buscar_noOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_noOrdenActionPerformed(evt);
            }
        });
        NoCuenta.add(btn_buscar_noOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, -1));
        NoCuenta.add(separador_nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 510, 10));

        panel_cancelaciones.add(NoCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 690, 500));

        NoOrden.setBackground(new java.awt.Color(255, 255, 255));

        cancelacion_noOrden.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        cancelacion_noOrden.setForeground(new java.awt.Color(0, 123, 164));
        cancelacion_noOrden.setText("Numero de orden");

        title_numero.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_numero.setForeground(new java.awt.Color(153, 153, 153));
        title_numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_numero.setText("Numero: ");

        input_numero.setFont(new java.awt.Font("Roboto Lt", 0, 24)); // NOI18N
        input_numero.setForeground(new java.awt.Color(153, 153, 153));
        input_numero.setBorder(null);

        btn_buscar_noOrden1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Btn_Buscar_Static_10.png"))); // NOI18N
        btn_buscar_noOrden1.setBorder(null);
        btn_buscar_noOrden1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_buscar_noOrden1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_buscar_noOrden1MouseExited(evt);
            }
        });
        btn_buscar_noOrden1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_noOrden1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NoOrdenLayout = new javax.swing.GroupLayout(NoOrden);
        NoOrden.setLayout(NoOrdenLayout);
        NoOrdenLayout.setHorizontalGroup(
            NoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoOrdenLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(cancelacion_noOrden)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoOrdenLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(NoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NoOrdenLayout.createSequentialGroup()
                            .addComponent(title_numero)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(input_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(separador_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_buscar_noOrden1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(87, 87, 87))
        );
        NoOrdenLayout.setVerticalGroup(
            NoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoOrdenLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cancelacion_noOrden)
                .addGap(29, 29, 29)
                .addGroup(NoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NoOrdenLayout.createSequentialGroup()
                        .addComponent(title_numero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(NoOrdenLayout.createSequentialGroup()
                        .addComponent(input_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btn_buscar_noOrden1)
                        .addGap(21, 21, 21))))
        );

        panel_cancelaciones.add(NoOrden, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 260));

        Resumen.setBackground(new java.awt.Color(244, 244, 244));

        title_cancelacionNo2.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        title_cancelacionNo2.setForeground(new java.awt.Color(102, 102, 102));
        title_cancelacionNo2.setText("Resumen");

        title_cancelacion_nombre.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title_cancelacion_nombre.setForeground(new java.awt.Color(0, 204, 255));
        title_cancelacion_nombre.setText("Nombre del cliente");

        title_cancelacionNo4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title_cancelacionNo4.setForeground(new java.awt.Color(0, 204, 255));
        title_cancelacionNo4.setText("No orden");

        title_cancelacion_noOrdern.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title_cancelacion_noOrdern.setForeground(new java.awt.Color(0, 204, 255));
        title_cancelacion_noOrdern.setText("#######");

        title_cancelacion_correo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title_cancelacion_correo.setForeground(new java.awt.Color(0, 204, 255));
        title_cancelacion_correo.setText("Correo@mail.com");

        title_cancelacion_telefono.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        title_cancelacion_telefono.setForeground(new java.awt.Color(0, 204, 255));
        title_cancelacion_telefono.setText("+52 993 311 3516");

        title_cancelacion_tour.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_cancelacion_tour.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_tour.setText("Tour: ");

        tour_cancelacion_nameTour.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_cancelacion_nameTour.setForeground(new java.awt.Color(153, 153, 153));
        tour_cancelacion_nameTour.setText("Tour Mane");

        title_cancelacion_date.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_cancelacion_date.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_date.setText("Date:");

        tour_cancelacion_date.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_cancelacion_date.setForeground(new java.awt.Color(153, 153, 153));
        tour_cancelacion_date.setText("00-month-0000");

        title_cancelacion_adult.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_cancelacion_adult.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_adult.setText("Adult:");

        tour_cancelacion_adult.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_cancelacion_adult.setForeground(new java.awt.Color(153, 153, 153));
        tour_cancelacion_adult.setText("00");

        title_cancelacion_child.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_cancelacion_child.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_child.setText("Child:");

        tour_cancelacion_child.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tour_cancelacion_child.setForeground(new java.awt.Color(153, 153, 153));
        tour_cancelacion_child.setText("00");

        title_cancelacion_time.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        title_cancelacion_time.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_time.setText("Time:");

        title_cancelacion_hora.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        title_cancelacion_hora.setForeground(new java.awt.Color(153, 153, 153));
        title_cancelacion_hora.setText("00:00 hrs");

        totalPrice.setFont(new java.awt.Font("Roboto", 0, 62)); // NOI18N
        totalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPrice.setText("$000.00");

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 123, 164));
        jLabel12.setText("Total");

        moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ag_btn_mx.png"))); // NOI18N
        moneda.setToolTipText("");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResumenLayout = new javax.swing.GroupLayout(Resumen);
        Resumen.setLayout(ResumenLayout);
        ResumenLayout.setHorizontalGroup(
            ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResumenLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addComponent(title_cancelacionNo2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ResumenLayout.createSequentialGroup()
                                .addComponent(title_cancelacion_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(title_cancelacion_telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(title_cancelacion_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(ResumenLayout.createSequentialGroup()
                                    .addComponent(title_cancelacionNo4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(title_cancelacion_noOrdern))))
                        .addGap(61, 61, 61))))
            .addGroup(ResumenLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addComponent(title_cancelacion_tour)
                        .addGap(5, 5, 5)
                        .addComponent(tour_cancelacion_nameTour, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addComponent(title_cancelacion_date)
                        .addGap(8, 8, 8)
                        .addComponent(tour_cancelacion_date, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(title_cancelacion_time)
                        .addGap(5, 5, 5)
                        .addComponent(title_cancelacion_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addComponent(title_cancelacion_adult)
                        .addGap(13, 13, 13)
                        .addComponent(tour_cancelacion_adult, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(title_cancelacion_child)
                        .addGap(14, 14, 14)
                        .addComponent(tour_cancelacion_child, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(ResumenLayout.createSequentialGroup()
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador_nombre1)
                    .addComponent(separador_nombre3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResumenLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(ResumenLayout.createSequentialGroup()
                        .addComponent(totalPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneda)))
                .addGap(117, 117, 117))
        );
        ResumenLayout.setVerticalGroup(
            ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResumenLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(title_cancelacionNo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title_cancelacion_nombre)
                .addGap(18, 18, 18)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_cancelacion_noOrdern)
                    .addComponent(title_cancelacionNo4))
                .addGap(18, 18, 18)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_cancelacion_correo)
                    .addComponent(title_cancelacion_telefono))
                .addGap(18, 18, 18)
                .addComponent(separador_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_cancelacion_tour)
                    .addComponent(tour_cancelacion_nameTour))
                .addGap(18, 18, 18)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_cancelacion_date)
                    .addComponent(tour_cancelacion_date)
                    .addComponent(title_cancelacion_time)
                    .addComponent(title_cancelacion_hora))
                .addGap(18, 18, 18)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_cancelacion_adult)
                    .addComponent(tour_cancelacion_adult)
                    .addComponent(title_cancelacion_child)
                    .addComponent(tour_cancelacion_child))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(separador_nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResumenLayout.createSequentialGroup()
                        .addGroup(ResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalPrice)
                            .addComponent(jButton1))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResumenLayout.createSequentialGroup()
                        .addComponent(moneda)
                        .addGap(56, 56, 56))))
        );

        panel_cancelaciones.add(Resumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 610, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_cancelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 1300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_cancelaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombreActionPerformed

    private void input_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_apellidoActionPerformed

    private void input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_emailActionPerformed

    private void input_celActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_celActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_celActionPerformed

    private void btn_buscar_noOrdenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_noOrdenMouseEntered
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Buscar_Hover_10.png"));
        this.btn_buscar_noOrden.setIcon(nepe);
    }//GEN-LAST:event_btn_buscar_noOrdenMouseEntered

    private void btn_buscar_noOrdenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_noOrdenMouseExited
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Buscar_Static_10.png"));
        this.btn_buscar_noOrden.setIcon(nepe);
    }//GEN-LAST:event_btn_buscar_noOrdenMouseExited

    private void btn_buscar_noOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_noOrdenActionPerformed
        // TODO add your handling code here: 
        ImageIcon nepe = new ImageIcon(getClass().getResource("/img/Btn_Buscar_Active_9.png"));
        this.btn_buscar_noOrden.setIcon(nepe);
    }//GEN-LAST:event_btn_buscar_noOrdenActionPerformed

    private void btn_buscar_noOrden1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_noOrden1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_noOrden1MouseEntered

    private void btn_buscar_noOrden1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscar_noOrden1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_noOrden1MouseExited

    private void btn_buscar_noOrden1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_noOrden1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_noOrden1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancelaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NoCuenta;
    private javax.swing.JPanel NoOrden;
    private javax.swing.JPanel Resumen;
    private javax.swing.JButton btn_buscar_noOrden;
    private javax.swing.JButton btn_buscar_noOrden1;
    private javax.swing.JLabel cancelacion_apellido;
    private javax.swing.JLabel cancelacion_cel;
    private javax.swing.JLabel cancelacion_email;
    private javax.swing.JLabel cancelacion_name;
    private javax.swing.JLabel cancelacion_noOrden;
    private javax.swing.JTextField input_apellido;
    private javax.swing.JTextField input_cel;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_nombre;
    private javax.swing.JTextField input_numero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel moneda;
    private javax.swing.JPanel panel_cancelaciones;
    private javax.swing.JSeparator separador_apellido;
    private javax.swing.JSeparator separador_cel;
    private javax.swing.JSeparator separador_email;
    private javax.swing.JSeparator separador_nombre1;
    private javax.swing.JSeparator separador_nombre2;
    private javax.swing.JSeparator separador_nombre3;
    private javax.swing.JSeparator separador_numero;
    private javax.swing.JLabel title_cancelacionNo;
    private javax.swing.JLabel title_cancelacionNo2;
    private javax.swing.JLabel title_cancelacionNo4;
    private javax.swing.JLabel title_cancelacion_adult;
    private javax.swing.JLabel title_cancelacion_child;
    private javax.swing.JLabel title_cancelacion_correo;
    private javax.swing.JLabel title_cancelacion_date;
    private javax.swing.JLabel title_cancelacion_hora;
    private javax.swing.JLabel title_cancelacion_noOrdern;
    private javax.swing.JLabel title_cancelacion_nombre;
    private javax.swing.JLabel title_cancelacion_telefono;
    private javax.swing.JLabel title_cancelacion_time;
    private javax.swing.JLabel title_cancelacion_tour;
    private javax.swing.JLabel title_numero;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JLabel tour_cancelacion_adult;
    private javax.swing.JLabel tour_cancelacion_child;
    private javax.swing.JLabel tour_cancelacion_date;
    private javax.swing.JLabel tour_cancelacion_nameTour;
    // End of variables declaration//GEN-END:variables
}
